-- Seed script for testing search and pagination functionality
-- This creates a variety of realistic canvassing data

INSERT INTO canvassing_notes (person_name, email, notes) VALUES
('Alice Johnson', 'alice.johnson@example.com', 'Very interested in climate change policies. Wants to volunteer for phone banking.'),
('Bob Smith', 'bob.smith@example.com', 'Concerned about healthcare costs. Has questions about Medicare expansion.'),
('Carol Davis', 'carol.davis@example.com', 'Strong supporter of education funding. Former teacher, very knowledgeable.'),
('David Wilson', NULL, 'Undecided voter. Wants more information about economic policies.'),
('Emma Brown', 'emma.brown@example.com', 'Young voter, first time participating. Interested in student loan forgiveness.'),
('Frank Miller', 'frank.miller@example.com', 'Small business owner worried about tax policies. Needs more details.'),
('Grace Taylor', 'grace.taylor@example.com', 'Environmental activist. Wants to know about renewable energy initiatives.'),
('Henry Anderson', NULL, 'Senior citizen focused on Social Security benefits and healthcare.'),
('Iris Chen', 'iris.chen@example.com', 'Tech worker interested in privacy and digital rights policies.'),
('Jack Robinson', 'jack.robinson@example.com', 'Veteran concerned about VA funding and military support programs.'),
('Karen Thompson', 'karen.thompson@example.com', 'Parent focused on child care policies and education funding.'),
('Leo Martinez', NULL, 'Construction worker interested in infrastructure and job creation programs.'),
('Maria Garcia', 'maria.garcia@example.com', 'Immigration advocate. Wants information about reform policies.'),
('Nathan White', 'nathan.white@example.com', 'College student interested in climate action and student debt relief.'),
('Olivia Jones', 'olivia.jones@example.com', 'Nurse concerned about healthcare worker conditions and patient care funding.'),
('Paul Lee', NULL, 'Farmer interested in agricultural subsidies and rural development programs.'),
('Quinn Davis', 'quinn.davis@example.com', 'Artist advocating for arts funding and cultural programs in schools.'),
('Rachel Green', 'rachel.green@example.com', 'Union member focused on worker rights and fair wage policies.'),
('Steve Clark', 'steve.clark@example.com', 'Retiree concerned about pension security and Medicare improvements.'),
('Tina Rodriguez', 'tina.rodriguez@example.com', 'Small business owner interested in startup funding and economic development.'),
('Uma Patel', NULL, 'Doctor concerned about public health funding and pandemic preparedness.'),
('Victor Kim', 'victor.kim@example.com', 'Engineer interested in infrastructure modernization and green technology.'),
('Wendy Adams', 'wendy.adams@example.com', 'Social worker advocating for mental health services and community programs.'),
('Xavier Foster', 'xavier.foster@example.com', 'Community organizer focused on housing affordability and urban development.'),
('Yuki Tanaka', 'yuki.tanaka@example.com', 'Graduate student researching environmental policy and sustainability initiatives.'),
('Zoe Campbell', NULL, 'Local business owner interested in downtown revitalization and tourism development.'),
('Alan Cooper', 'alan.cooper@example.com', 'Coach interested in youth sports funding and community recreation programs.'),
('Betty Nelson', 'betty.nelson@example.com', 'Librarian advocating for public library funding and literacy programs.'),
('Carlos Ruiz', 'carlos.ruiz@example.com', 'Electrician interested in renewable energy jobs and green infrastructure.'),
('Diana King', NULL, 'Volunteer coordinator focused on nonprofit funding and community service programs.'),
('Edward Hayes', 'edward.hayes@example.com', 'Police officer interested in community policing and public safety funding.'),
('Fiona Murphy', 'fiona.murphy@example.com', 'Nurse practitioner advocating for rural healthcare access and telemedicine.'),
('George Price', 'george.price@example.com', 'Mechanic interested in electric vehicle infrastructure and automotive industry support.'),
('Helen Scott', NULL, 'Teacher focused on special education funding and classroom resource allocation.'),
('Ian Torres', 'ian.torres@example.com', 'Firefighter concerned about emergency services funding and equipment updates.'),
('Julia Ward', 'julia.ward@example.com', 'Accountant interested in tax policy transparency and small business support.'),
('Kevin Bell', 'kevin.bell@example.com', 'Paramedic advocating for emergency medical services and first responder support.'),
('Linda Gray', 'linda.gray@example.com', 'Counselor focused on mental health services and substance abuse programs.'),
('Michael Reed', NULL, 'Carpenter interested in construction jobs and infrastructure investment.'),
('Nancy Phillips', 'nancy.phillips@example.com', 'Pharmacist concerned about prescription drug costs and healthcare accessibility.'),
('Oscar Evans', 'oscar.evans@example.com', 'Park ranger interested in environmental conservation and outdoor recreation funding.'),
('Patricia Hill', 'patricia.hill@example.com', 'Social service coordinator advocating for family support and childcare programs.'),
('Quincy Baker', NULL, 'Chef interested in food safety regulations and local agriculture support.'),
('Rita Morgan', 'rita.morgan@example.com', 'Physical therapist focused on disability services and accessibility improvements.'),
('Samuel Wright', 'samuel.wright@example.com', 'IT specialist interested in broadband expansion and digital equity programs.'),
('Teresa Lopez', 'teresa.lopez@example.com', 'Dental hygienist advocating for public health and preventive care funding.'),
('Ulysses James', NULL, 'Bus driver interested in public transportation funding and infrastructure improvements.'),
('Veronica Long', 'veronica.long@example.com', 'Journalist focused on press freedom and public information transparency.'),
('William Hall', 'william.hall@example.com', 'Security guard interested in job training programs and economic opportunity.'),
('Xiomara Rivera', 'xiomara.rivera@example.com', 'Translator advocating for language services and immigrant community support.'),
('Yvonne Carter', NULL, 'Cashier interested in minimum wage policies and worker protection programs.'),
('Zachary Collins', 'zachary.collins@example.com', 'Personal trainer focused on public health initiatives and community wellness programs.');
